-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 23:03:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ServiciosTJ
-- -----------------------------------------------------
-- Schema para aplicaciones Empresa donde Trabaja Kania.
DROP SCHEMA IF EXISTS `ServiciosTJ` ;

-- -----------------------------------------------------
-- Schema ServiciosTJ
--
-- Schema para aplicaciones Empresa donde Trabaja Kania.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ServiciosTJ` DEFAULT CHARACTER SET utf8 ;
USE `ServiciosTJ` ;

-- -----------------------------------------------------
-- Table `ServiciosTJ`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiciosTJ`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ServiciosTJ`.`Cliente` (
  `nit` INT NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`nit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiciosTJ`.`Remision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiciosTJ`.`Remision` ;

CREATE TABLE IF NOT EXISTS `ServiciosTJ`.`Remision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` CHAR(2) NOT NULL,
  `fecha` DATE NOT NULL,
  `Cliente_nit` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Remision_Cliente1_idx` (`Cliente_nit` ASC),
  CONSTRAINT `fk_Remision_Cliente1`
    FOREIGN KEY (`Cliente_nit`)
    REFERENCES `ServiciosTJ`.`Cliente` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiciosTJ`.`Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiciosTJ`.`Material` ;

CREATE TABLE IF NOT EXISTS `ServiciosTJ`.`Material` (
  `codigo` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `peso` DECIMAL(10,2) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiciosTJ`.`Material_Remision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiciosTJ`.`Material_Remision` ;

CREATE TABLE IF NOT EXISTS `ServiciosTJ`.`Material_Remision` (
  `Remision_id` INT NOT NULL,
  `Material_codigo` VARCHAR(15) NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 0,
  INDEX `fk_Material_Remision_Remision1_idx` (`Remision_id` ASC),
  INDEX `fk_Material_Remision_Material1_idx` (`Material_codigo` ASC),
  CONSTRAINT `fk_Material_Remision_Remision1`
    FOREIGN KEY (`Remision_id`)
    REFERENCES `ServiciosTJ`.`Remision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_Remision_Material1`
    FOREIGN KEY (`Material_codigo`)
    REFERENCES `ServiciosTJ`.`Material` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiciosTJ`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiciosTJ`.`Factura` ;

CREATE TABLE IF NOT EXISTS `ServiciosTJ`.`Factura` (
  `id` INT NOT NULL,
  `fecha_generacion` VARCHAR(45) NOT NULL,
  `fecha_corte` DATE NOT NULL,
  `Cliente_nit` INT NOT NULL,
  `subtototal` DECIMAL(10,2) NULL,
  `iva` DECIMAL(10,2) NULL,
  `total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_nit` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_nit`)
    REFERENCES `ServiciosTJ`.`Cliente` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiciosTJ`.`Factura_Remision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ServiciosTJ`.`Factura_Remision` ;

CREATE TABLE IF NOT EXISTS `ServiciosTJ`.`Factura_Remision` (
  `Factura_id` INT NOT NULL,
  `Remision_id` INT NOT NULL,
  INDEX `fk_Factura_Remision_Factura1_idx` (`Factura_id` ASC),
  INDEX `fk_Factura_Remision_Remision1_idx` (`Remision_id` ASC),
  CONSTRAINT `fk_Factura_Remision_Factura1`
    FOREIGN KEY (`Factura_id`)
    REFERENCES `ServiciosTJ`.`Factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Remision_Remision1`
    FOREIGN KEY (`Remision_id`)
    REFERENCES `ServiciosTJ`.`Remision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
